name: involved
description: Involved mpbile application
version: 1.0.0+1

environment:
  sdk: ">=2.11.0 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_bloc: ^7.3.0
  get_it: ^7.2.0
  equatable: ^2.0.3
  dartz: ^0.10.0
  shared_preferences: ^2.0.8
  connectivity: ^3.0.6
  page_transition: ^2.0.4
  flutter_spinkit: ^5.1.0
  flutter_svg: ^1.0.0
  google_fonts: ^2.3.2
  shimmer: ^2.0.0
  fancy_shimmer_image: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - images/svg/
    - images/png/
